<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOnvuzlf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOnvuzlf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOnvuzlf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOnvuzlf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOnvuzlf\appProdProjectContainer([
    'container.build_hash' => 'Onvuzlf',
    'container.build_id' => '760397fc',
    'container.build_time' => 1720692528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOnvuzlf');
